export const BINGO_ITEMS = [
  "(animal noises in the background)",
  "Is ______ on the call?",
  "We do have 5 minutes left",
  "Hello, hello?",
  "Could you please get closer to the mic?",
  "I was having connection issues",
  "Sorry, IO had problems loging in",
  "Can you email that to everyone?",
  "Can you repeat please?",
  "Sorry, something ______ with my calendar",
  "(child noises in the background)",
  "Could you share this slides afterwards?",
  "Sorry, I didn't find the conference id",
  "You will send the minutes?",
  "I need to jump in another call",
  "Can everyone go on mute",
  "Can we take this offline?",
  "Do you see my screen?",
  "Is everyone in the call?",
  "Can somebody grant presenter rights?",
  "Sorry, I was on mute",
  "Next slide, please",
  "Who just joined?",
  "I think you're on mute",
  "Sorry, can you hear me now?",
  "Let's circle back to that",
  "Can we take a 5-minute break?",
  "Let's table that for later",
  "Please update your status",
  "Can you put that in the chat?",
  "Let's give everyone a minute to join",
  "We'll wait for the others",
  "I’ll follow up with you after this",
  "We’re waiting for the host",
  "I think there's a lag",
  "Can you adjust your volume?",
  "Can we stick to the agenda?",
  "I think we lost someone",
  "Can you re-share your screen?",
  "Let's reconvene next week",
  "I think someone’s mic is on",
  "Can you please speak louder?",
  "Let's move to the next point",
  "Sorry, I was multitasking",
  "Can you summarize that?",
  "We’ll circle back offline",
  "Let me check and get back to you",
];
